name: 'Taskade ESLint TSC Action'
description: 'Provide ESLint and TSC check annotations on PRs'
inputs:
  check_name:
    description: Name for the check run
    required: false
  github_token:
    description: 'GitHub token'
    required: true
    default: ${{ github.token }}
  extensions:
    description: 'File extensions to lint, comma-separated. Includes the period.'
    required: false
    default: '.js,.jsx,.ts,.tsx'
runs:
  using: 'node12'
  main: 'lib/index.js'
